// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AcceptanceTest
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Customer Status")]
    public partial class CustomerStatusFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CustomerStatus.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Customer Status", "In order to make a better profit\r\nAs a salesman\r\nI want to be able to change the " +
                    "status of a customer so they may receive a discount", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Customer Status Discount")]
        [NUnit.Framework.TestCaseAttribute("Normal", "0", "100", "100", new string[0])]
        [NUnit.Framework.TestCaseAttribute("HighRoller", "10", "100", "90", new string[0])]
        [NUnit.Framework.TestCaseAttribute("VIP", "20", "100", "80", new string[0])]
        public virtual void CustomerStatusDiscount(string customerStatus, string discount, string calculatedBill, string billWithDiscount, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Customer Status Discount", exampleTags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given(string.Format("I have given a customer the \"{0}\" status", customerStatus));
#line 8
 testRunner.And(string.Format("I charge {0} pr Voice Call", calculatedBill));
#line 9
 testRunner.And("the customer has finished a call");
#line 10
 testRunner.When(string.Format("I calculate the cost of the customers bill to {0}", calculatedBill));
#line 11
 testRunner.Then(string.Format("bill receives a {0}% discount", discount));
#line 12
 testRunner.And(string.Format("the final bill is {0}", billWithDiscount));
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
