// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AcceptanceTest
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Phone Subscription")]
    public partial class PhoneSubscriptionFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PhoneSubscription.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Phone Subscription", "In order to make a better profit on phones\r\nAs an accountant\r\nI want to be able t" +
                    "o define subscriptions which consists of one or more services\r\nAnd register the " +
                    "usage of these services", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create A New Subscription")]
        public virtual void CreateANewSubscription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create A New Subscription", ((string[])(null)));
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I want to create a new subscription");
#line 9
 testRunner.When("I have created the subscription");
#line 10
 testRunner.Then("the subscription always consists of an empty list of Inland services");
#line 11
 testRunner.And("an empty list of Abroad services");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can add a service to a subscription")]
        public virtual void CanAddAServiceToASubscription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can add a service to a subscription", ((string[])(null)));
#line 13
this.ScenarioSetup(scenarioInfo);
#line 14
 testRunner.Given("I have a subscription");
#line 15
 testRunner.When("I add a new Voice Call service to the Inland services");
#line 16
 testRunner.And("I add a new Voice Call service to the Abroad services");
#line 17
 testRunner.Then("the Voice Call service must be added the Inland services");
#line 18
 testRunner.And("the Voice Call service must be added the Abroad services");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cannot add a service to a subscription with existing service of same type")]
        public virtual void CannotAddAServiceToASubscriptionWithExistingServiceOfSameType()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot add a service to a subscription with existing service of same type", ((string[])(null)));
#line 20
this.ScenarioSetup(scenarioInfo);
#line 21
 testRunner.Given("I have a subscription");
#line 22
 testRunner.And("the Inland services allready contains a Voice Call service");
#line 23
 testRunner.And("the Abroad services allready contains a Voice Call service");
#line 24
 testRunner.When("I add a new Voice Call service to the Inland services");
#line 25
 testRunner.And("I add a new Voice Call service to the Abroad services");
#line 26
 testRunner.Then("the Voice Call service is not added the Inland services");
#line 27
 testRunner.And("the Voice Call service is not added the Abroad services");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
