// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AcceptanceTest
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SMS Service - Register Call")]
    public partial class SMSService_RegisterCallFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SMS Service - Register Call.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SMS Service - Register Call", "In order to make a profit on sms calls\r\nAs an accountant\r\nI must be able to regis" +
                    "ter sms calls by a set of parameters to calculate the bill for a customer", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Register Local SMS Call")]
        [NUnit.Framework.TestCaseAttribute("09:00:00", "128", "98561234", "DK", "DK", new string[0])]
        [NUnit.Framework.TestCaseAttribute("15:41:02", "256", "23458126", "DK", "DK", new string[0])]
        [NUnit.Framework.TestCaseAttribute("18:29:56", "512", "98561234", "DK", "DK", new string[0])]
        public virtual void RegisterLocalSMSCall(string sentTime, string lenght, string receiver, string sourceCountry, string destinationCountry, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Register Local SMS Call", exampleTags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("a subscription with phone number \"77889955\" exists");
#line 8
 testRunner.And("the subscription includes the SMS Service");
#line 9
 testRunner.And("the customer creates an SMS");
#line 10
 testRunner.And(string.Format("the SMS has the lenght \"{0}\" characters", lenght));
#line 11
 testRunner.And(string.Format("the SMS is sent to number: \"{0}\"", receiver));
#line 12
 testRunner.And(string.Format("the SMS is sent from: \"{0}\"", sourceCountry));
#line 13
 testRunner.And(string.Format("the SMS is sent to: \"{0}\"", destinationCountry));
#line 14
 testRunner.When(string.Format("the SMS is sent at \"{0}\"", sentTime));
#line 15
 testRunner.Then("I must be able to find the SMS using the subscription");
#line 16
 testRunner.And(string.Format("the start time of the SMS must be registered at \"{0}\"", sentTime));
#line 17
 testRunner.And(string.Format("the lenght of the SMS must be registered to be \"{0}\" characters", lenght));
#line 18
 testRunner.And(string.Format("the receiver of the SMS must be registered as \"{0}\"", receiver));
#line 19
 testRunner.And(string.Format("the country from which the SMS was sent from must be registered as \"{0}\"", sourceCountry));
#line 20
 testRunner.And(string.Format("the country for which the SMS was sent to must be registered as \"{0}\"", destinationCountry));
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Register Foreign SMS Call")]
        [NUnit.Framework.TestCaseAttribute("09:00:00", "128", "98561234", "DK", "DE", new string[0])]
        [NUnit.Framework.TestCaseAttribute("15:41:02", "256", "23458126", "DE", "DK", new string[0])]
        [NUnit.Framework.TestCaseAttribute("18:29:56", "512", "98561234", "DE", "DE", new string[0])]
        public virtual void RegisterForeignSMSCall(string sentTime, string lenght, string receiver, string sourceCountry, string destinationCountry, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Register Foreign SMS Call", exampleTags);
#line 29
this.ScenarioSetup(scenarioInfo);
#line 30
 testRunner.Given("a subscription with phone number \"77889955\" exists");
#line 31
 testRunner.And("the subscription includes the SMS Service");
#line 32
 testRunner.And(string.Format("the subscription includes support for texting from country: \"{0}\"", sourceCountry));
#line 33
 testRunner.And(string.Format("the subscription includes support for texting to country: \"{0}\"", destinationCountry));
#line 34
 testRunner.And("the customer creates an SMS");
#line 35
 testRunner.And(string.Format("the SMS has the lenght \"{0}\" characters", lenght));
#line 36
 testRunner.And(string.Format("the SMS is sent to number: \"{0}\"", receiver));
#line 37
 testRunner.And(string.Format("the SMS is sent from: \"{0}\"", sourceCountry));
#line 38
 testRunner.And(string.Format("the SMS is sent to: \"{0}\"", destinationCountry));
#line 39
 testRunner.When(string.Format("the SMS is sent at \"{0}\"", sentTime));
#line 40
 testRunner.Then("I must be able to find the SMS using the subscription");
#line 41
 testRunner.And(string.Format("the start time of the SMS must be registered at \"{0}\"", sentTime));
#line 42
 testRunner.And(string.Format("the lenght of the SMS must be registered to be \"{0}\" characters", lenght));
#line 43
 testRunner.And(string.Format("the receiver of the SMS must be registered as \"{0}\"", receiver));
#line 44
 testRunner.And(string.Format("the country from which the SMS was sent from must be registered as \"{0}\"", sourceCountry));
#line 45
 testRunner.And(string.Format("the country for which the SMS was sent to must be registered as \"{0}\"", destinationCountry));
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
